/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const SourceKind = IDL.Variant({
  'pdf' : IDL.Null,
  'url' : IDL.Null,
  'docx' : IDL.Null,
  'note' : IDL.Null,
  'pptx' : IDL.Null,
  'text' : IDL.Null,
  'youtube' : IDL.Null,
});
export const NotebookId = IDL.Nat;
export const SourceInput = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'kind' : SourceKind,
  'storageKey' : IDL.Text,
  'sizeBytes' : IDL.Nat,
  'notebookId' : NotebookId,
});
export const SourceId = IDL.Nat;
export const SourceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processing' : IDL.Null,
  'ready' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Source = IDL.Record({
  'id' : SourceId,
  'url' : IDL.Text,
  'status' : SourceStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : UserId,
  'kind' : SourceKind,
  'createdAt' : Timestamp,
  'errorMessage' : IDL.Text,
  'updatedAt' : Timestamp,
  'storageKey' : IDL.Text,
  'sizeBytes' : IDL.Nat,
  'notebookId' : NotebookId,
  'pageCount' : IDL.Nat,
});
export const AppError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'unsupportedSourceKind' : IDL.Text,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Text,
  'engineUnavailable' : IDL.Text,
  'sourceTooLarge' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : Source, 'err' : AppError });
export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Citation = IDL.Record({
  'sourceTitle' : IDL.Text,
  'sourceId' : SourceId,
  'snippet' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'conversationId' : ConversationId,
  'citations' : IDL.Vec(Citation),
  'notebookId' : NotebookId,
});
export const Answer = IDL.Record({
  'assistantMessage' : Message,
  'userMessage' : Message,
  'conversationId' : ConversationId,
});
export const Result_6 = IDL.Variant({ 'ok' : Answer, 'err' : AppError });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notebookId' : NotebookId,
});
export const Result_5 = IDL.Variant({ 'ok' : Conversation, 'err' : AppError });
export const NotebookInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Notebook = IDL.Record({
  'id' : NotebookId,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const NoteId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'exam' : IDL.Null,
});
export const FlashcardRequest = IDL.Record({
  'difficulty' : Difficulty,
  'count' : IDL.Nat,
  'sourceId' : IDL.Opt(SourceId),
  'notebookId' : NotebookId,
});
export const FlashcardId = IDL.Nat;
export const Flashcard = IDL.Record({
  'id' : FlashcardId,
  'front' : IDL.Text,
  'owner' : UserId,
  'back' : IDL.Text,
  'createdAt' : Timestamp,
  'reviewCount' : IDL.Nat,
  'notebookId' : NotebookId,
  'lastReviewedAt' : IDL.Opt(Timestamp),
  'knownCount' : IDL.Nat,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(Flashcard),
  'err' : AppError,
});
export const StudyMaterialKind = IDL.Variant({
  'quiz' : IDL.Null,
  'summary' : IDL.Null,
  'detailedNotes' : IDL.Null,
  'flashcards' : IDL.Null,
});
export const NoteRequest = IDL.Record({
  'kind' : StudyMaterialKind,
  'difficulty' : Difficulty,
  'sourceId' : IDL.Opt(SourceId),
  'notebookId' : NotebookId,
  'chapter' : IDL.Opt(IDL.Text),
});
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : UserId,
  'kind' : StudyMaterialKind,
  'difficulty' : Difficulty,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notebookId' : NotebookId,
});
export const Result_3 = IDL.Variant({ 'ok' : Note, 'err' : AppError });
export const QuizDifficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const QuestionKind = IDL.Variant({
  'mcq' : IDL.Null,
  'shortAnswer' : IDL.Null,
  'trueFalse' : IDL.Null,
});
export const QuizRequest = IDL.Record({
  'difficulty' : QuizDifficulty,
  'count' : IDL.Nat,
  'sourceId' : IDL.Opt(SourceId),
  'notebookId' : NotebookId,
  'kinds' : IDL.Vec(QuestionKind),
});
export const QuizId = IDL.Nat;
export const Quiz = IDL.Record({
  'id' : QuizId,
  'title' : IDL.Text,
  'owner' : UserId,
  'difficulty' : QuizDifficulty,
  'createdAt' : Timestamp,
  'notebookId' : NotebookId,
});
export const Result_2 = IDL.Variant({ 'ok' : Quiz, 'err' : AppError });
export const ProgressId = IDL.Nat;
export const StudyProgress = IDL.Record({
  'id' : ProgressId,
  'questionsAnswered' : IDL.Nat,
  'notesGenerated' : IDL.Nat,
  'owner' : UserId,
  'quizzesTaken' : IDL.Nat,
  'questionsCorrect' : IDL.Nat,
  'notebookId' : NotebookId,
  'lastActivityAt' : Timestamp,
  'flashcardsReviewed' : IDL.Nat,
});
export const QuestionId = IDL.Nat;
export const QuizQuestionView = IDL.Record({
  'id' : QuestionId,
  'topic' : IDL.Text,
  'kind' : QuestionKind,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'notebookId' : NotebookId,
});
export const ConversationSummary = IDL.Record({
  'conversation' : Conversation,
  'messageCount' : IDL.Nat,
});
export const NotebookSummary = IDL.Record({
  'conversationCount' : IDL.Nat,
  'notebook' : Notebook,
  'sourceCount' : IDL.Nat,
  'flashcardCount' : IDL.Nat,
  'noteCount' : IDL.Nat,
  'quizCount' : IDL.Nat,
});
export const SourceSummary = IDL.Record({
  'source' : Source,
  'chunkCount' : IDL.Nat,
});
export const SearchHit = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'kind' : IDL.Text,
  'snippet' : IDL.Text,
  'notebookId' : NotebookId,
});
export const QuizAnswer = IDL.Record({
  'questionId' : QuestionId,
  'selectedIndex' : IDL.Nat,
});
export const QuizResultItem = IDL.Record({
  'topic' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'correct' : IDL.Bool,
  'questionId' : QuestionId,
  'selectedIndex' : IDL.Nat,
  'prompt' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'wrongCount' : IDL.Nat,
  'total' : IDL.Nat,
  'weakTopics' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
  'items' : IDL.Vec(QuizResultItem),
  'correctCount' : IDL.Nat,
  'quizId' : QuizId,
  'recommendedRevision' : IDL.Vec(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : QuizResult, 'err' : AppError });
export const NotebookUpdate = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addSource' : IDL.Func([SourceInput], [Result_1], []),
  'askQuestion' : IDL.Func([ConversationId, IDL.Text], [Result_6], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([NotebookId, IDL.Text], [Result_5], []),
  'createNotebook' : IDL.Func([NotebookInput], [Notebook], []),
  'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
  'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'deleteNotebook' : IDL.Func([NotebookId], [IDL.Bool], []),
  'deleteSource' : IDL.Func([SourceId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'generateFlashcards' : IDL.Func([FlashcardRequest], [Result_4], []),
  'generateNote' : IDL.Func([NoteRequest], [Result_3], []),
  'generateQuiz' : IDL.Func([QuizRequest], [Result_2], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'getNotebook' : IDL.Func([NotebookId], [IDL.Opt(Notebook)], ['query']),
  'getProgress' : IDL.Func([NotebookId], [IDL.Opt(StudyProgress)], ['query']),
  'getQuiz' : IDL.Func(
      [QuizId],
      [IDL.Opt(IDL.Tuple(Quiz, IDL.Vec(QuizQuestionView)))],
      ['query'],
    ),
  'getSource' : IDL.Func([SourceId], [IDL.Opt(Source)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChapters' : IDL.Func([NotebookId], [IDL.Vec(Chapter)], ['query']),
  'listConversations' : IDL.Func(
      [NotebookId],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'listFlashcards' : IDL.Func([NotebookId], [IDL.Vec(Flashcard)], ['query']),
  'listMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'listNotebooks' : IDL.Func([], [IDL.Vec(NotebookSummary)], ['query']),
  'listNotes' : IDL.Func([NotebookId], [IDL.Vec(Note)], ['query']),
  'listQuizzes' : IDL.Func([NotebookId], [IDL.Vec(Quiz)], ['query']),
  'listSources' : IDL.Func([NotebookId], [IDL.Vec(SourceSummary)], ['query']),
  'processSource' : IDL.Func([SourceId], [Result_1], []),
  'reviewFlashcard' : IDL.Func(
      [FlashcardId, IDL.Bool],
      [IDL.Opt(Flashcard)],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'search' : IDL.Func([IDL.Text], [IDL.Vec(SearchHit)], ['query']),
  'seedDemoData' : IDL.Func([], [Notebook], []),
  'setChapters' : IDL.Func(
      [NotebookId, IDL.Vec(IDL.Text)],
      [IDL.Vec(Chapter)],
      [],
    ),
  'submitQuiz' : IDL.Func([QuizId, IDL.Vec(QuizAnswer)], [Result], []),
  'updateNote' : IDL.Func(
      [NoteId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Opt(Note)],
      [],
    ),
  'updateNotebook' : IDL.Func(
      [NotebookId, NotebookUpdate],
      [IDL.Opt(Notebook)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const SourceKind = IDL.Variant({
    'pdf' : IDL.Null,
    'url' : IDL.Null,
    'docx' : IDL.Null,
    'note' : IDL.Null,
    'pptx' : IDL.Null,
    'text' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const NotebookId = IDL.Nat;
  const SourceInput = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'kind' : SourceKind,
    'storageKey' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'notebookId' : NotebookId,
  });
  const SourceId = IDL.Nat;
  const SourceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processing' : IDL.Null,
    'ready' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Source = IDL.Record({
    'id' : SourceId,
    'url' : IDL.Text,
    'status' : SourceStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : UserId,
    'kind' : SourceKind,
    'createdAt' : Timestamp,
    'errorMessage' : IDL.Text,
    'updatedAt' : Timestamp,
    'storageKey' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'notebookId' : NotebookId,
    'pageCount' : IDL.Nat,
  });
  const AppError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'unsupportedSourceKind' : IDL.Text,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Text,
    'engineUnavailable' : IDL.Text,
    'sourceTooLarge' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : Source, 'err' : AppError });
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Citation = IDL.Record({
    'sourceTitle' : IDL.Text,
    'sourceId' : SourceId,
    'snippet' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'role' : MessageRole,
    'conversationId' : ConversationId,
    'citations' : IDL.Vec(Citation),
    'notebookId' : NotebookId,
  });
  const Answer = IDL.Record({
    'assistantMessage' : Message,
    'userMessage' : Message,
    'conversationId' : ConversationId,
  });
  const Result_6 = IDL.Variant({ 'ok' : Answer, 'err' : AppError });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notebookId' : NotebookId,
  });
  const Result_5 = IDL.Variant({ 'ok' : Conversation, 'err' : AppError });
  const NotebookInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Notebook = IDL.Record({
    'id' : NotebookId,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const NoteId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'exam' : IDL.Null,
  });
  const FlashcardRequest = IDL.Record({
    'difficulty' : Difficulty,
    'count' : IDL.Nat,
    'sourceId' : IDL.Opt(SourceId),
    'notebookId' : NotebookId,
  });
  const FlashcardId = IDL.Nat;
  const Flashcard = IDL.Record({
    'id' : FlashcardId,
    'front' : IDL.Text,
    'owner' : UserId,
    'back' : IDL.Text,
    'createdAt' : Timestamp,
    'reviewCount' : IDL.Nat,
    'notebookId' : NotebookId,
    'lastReviewedAt' : IDL.Opt(Timestamp),
    'knownCount' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(Flashcard), 'err' : AppError });
  const StudyMaterialKind = IDL.Variant({
    'quiz' : IDL.Null,
    'summary' : IDL.Null,
    'detailedNotes' : IDL.Null,
    'flashcards' : IDL.Null,
  });
  const NoteRequest = IDL.Record({
    'kind' : StudyMaterialKind,
    'difficulty' : Difficulty,
    'sourceId' : IDL.Opt(SourceId),
    'notebookId' : NotebookId,
    'chapter' : IDL.Opt(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : UserId,
    'kind' : StudyMaterialKind,
    'difficulty' : Difficulty,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notebookId' : NotebookId,
  });
  const Result_3 = IDL.Variant({ 'ok' : Note, 'err' : AppError });
  const QuizDifficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const QuestionKind = IDL.Variant({
    'mcq' : IDL.Null,
    'shortAnswer' : IDL.Null,
    'trueFalse' : IDL.Null,
  });
  const QuizRequest = IDL.Record({
    'difficulty' : QuizDifficulty,
    'count' : IDL.Nat,
    'sourceId' : IDL.Opt(SourceId),
    'notebookId' : NotebookId,
    'kinds' : IDL.Vec(QuestionKind),
  });
  const QuizId = IDL.Nat;
  const Quiz = IDL.Record({
    'id' : QuizId,
    'title' : IDL.Text,
    'owner' : UserId,
    'difficulty' : QuizDifficulty,
    'createdAt' : Timestamp,
    'notebookId' : NotebookId,
  });
  const Result_2 = IDL.Variant({ 'ok' : Quiz, 'err' : AppError });
  const ProgressId = IDL.Nat;
  const StudyProgress = IDL.Record({
    'id' : ProgressId,
    'questionsAnswered' : IDL.Nat,
    'notesGenerated' : IDL.Nat,
    'owner' : UserId,
    'quizzesTaken' : IDL.Nat,
    'questionsCorrect' : IDL.Nat,
    'notebookId' : NotebookId,
    'lastActivityAt' : Timestamp,
    'flashcardsReviewed' : IDL.Nat,
  });
  const QuestionId = IDL.Nat;
  const QuizQuestionView = IDL.Record({
    'id' : QuestionId,
    'topic' : IDL.Text,
    'kind' : QuestionKind,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'notebookId' : NotebookId,
  });
  const ConversationSummary = IDL.Record({
    'conversation' : Conversation,
    'messageCount' : IDL.Nat,
  });
  const NotebookSummary = IDL.Record({
    'conversationCount' : IDL.Nat,
    'notebook' : Notebook,
    'sourceCount' : IDL.Nat,
    'flashcardCount' : IDL.Nat,
    'noteCount' : IDL.Nat,
    'quizCount' : IDL.Nat,
  });
  const SourceSummary = IDL.Record({
    'source' : Source,
    'chunkCount' : IDL.Nat,
  });
  const SearchHit = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'kind' : IDL.Text,
    'snippet' : IDL.Text,
    'notebookId' : NotebookId,
  });
  const QuizAnswer = IDL.Record({
    'questionId' : QuestionId,
    'selectedIndex' : IDL.Nat,
  });
  const QuizResultItem = IDL.Record({
    'topic' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'correct' : IDL.Bool,
    'questionId' : QuestionId,
    'selectedIndex' : IDL.Nat,
    'prompt' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'wrongCount' : IDL.Nat,
    'total' : IDL.Nat,
    'weakTopics' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
    'items' : IDL.Vec(QuizResultItem),
    'correctCount' : IDL.Nat,
    'quizId' : QuizId,
    'recommendedRevision' : IDL.Vec(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : QuizResult, 'err' : AppError });
  const NotebookUpdate = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addSource' : IDL.Func([SourceInput], [Result_1], []),
    'askQuestion' : IDL.Func([ConversationId, IDL.Text], [Result_6], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([NotebookId, IDL.Text], [Result_5], []),
    'createNotebook' : IDL.Func([NotebookInput], [Notebook], []),
    'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
    'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'deleteNotebook' : IDL.Func([NotebookId], [IDL.Bool], []),
    'deleteSource' : IDL.Func([SourceId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'generateFlashcards' : IDL.Func([FlashcardRequest], [Result_4], []),
    'generateNote' : IDL.Func([NoteRequest], [Result_3], []),
    'generateQuiz' : IDL.Func([QuizRequest], [Result_2], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'getNotebook' : IDL.Func([NotebookId], [IDL.Opt(Notebook)], ['query']),
    'getProgress' : IDL.Func([NotebookId], [IDL.Opt(StudyProgress)], ['query']),
    'getQuiz' : IDL.Func(
        [QuizId],
        [IDL.Opt(IDL.Tuple(Quiz, IDL.Vec(QuizQuestionView)))],
        ['query'],
      ),
    'getSource' : IDL.Func([SourceId], [IDL.Opt(Source)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChapters' : IDL.Func([NotebookId], [IDL.Vec(Chapter)], ['query']),
    'listConversations' : IDL.Func(
        [NotebookId],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'listFlashcards' : IDL.Func([NotebookId], [IDL.Vec(Flashcard)], ['query']),
    'listMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'listNotebooks' : IDL.Func([], [IDL.Vec(NotebookSummary)], ['query']),
    'listNotes' : IDL.Func([NotebookId], [IDL.Vec(Note)], ['query']),
    'listQuizzes' : IDL.Func([NotebookId], [IDL.Vec(Quiz)], ['query']),
    'listSources' : IDL.Func([NotebookId], [IDL.Vec(SourceSummary)], ['query']),
    'processSource' : IDL.Func([SourceId], [Result_1], []),
    'reviewFlashcard' : IDL.Func(
        [FlashcardId, IDL.Bool],
        [IDL.Opt(Flashcard)],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'search' : IDL.Func([IDL.Text], [IDL.Vec(SearchHit)], ['query']),
    'seedDemoData' : IDL.Func([], [Notebook], []),
    'setChapters' : IDL.Func(
        [NotebookId, IDL.Vec(IDL.Text)],
        [IDL.Vec(Chapter)],
        [],
      ),
    'submitQuiz' : IDL.Func([QuizId, IDL.Vec(QuizAnswer)], [Result], []),
    'updateNote' : IDL.Func(
        [NoteId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Opt(Note)],
        [],
      ),
    'updateNotebook' : IDL.Func(
        [NotebookId, NotebookUpdate],
        [IDL.Opt(Notebook)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };