/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'assistantMessage' : Message,
  'userMessage' : Message,
  'conversationId' : ConversationId,
}
export type AppError = { 'notAuthorized' : null } |
  { 'unsupportedSourceKind' : string } |
  { 'invalidInput' : string } |
  { 'notFound' : string } |
  { 'engineUnavailable' : string } |
  { 'sourceTooLarge' : string };
export interface Cell { 'value' : Value, 'name' : string }
export interface Chapter {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'notebookId' : NotebookId,
}
export interface Citation {
  'sourceTitle' : string,
  'sourceId' : SourceId,
  'snippet' : string,
}
export interface Conversation {
  'id' : ConversationId,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notebookId' : NotebookId,
}
export type ConversationId = bigint;
export interface ConversationSummary {
  'conversation' : Conversation,
  'messageCount' : bigint,
}
export type Difficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'exam' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Flashcard {
  'id' : FlashcardId,
  'front' : string,
  'owner' : UserId,
  'back' : string,
  'createdAt' : Timestamp,
  'reviewCount' : bigint,
  'notebookId' : NotebookId,
  'lastReviewedAt' : [] | [Timestamp],
  'knownCount' : bigint,
}
export type FlashcardId = bigint;
export interface FlashcardRequest {
  'difficulty' : Difficulty,
  'count' : bigint,
  'sourceId' : [] | [SourceId],
  'notebookId' : NotebookId,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'conversationId' : ConversationId,
  'citations' : Array<Citation>,
  'notebookId' : NotebookId,
}
export type MessageId = bigint;
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export interface Note {
  'id' : NoteId,
  'title' : string,
  'content' : string,
  'owner' : UserId,
  'kind' : StudyMaterialKind,
  'difficulty' : Difficulty,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notebookId' : NotebookId,
}
export type NoteId = bigint;
export interface NoteRequest {
  'kind' : StudyMaterialKind,
  'difficulty' : Difficulty,
  'sourceId' : [] | [SourceId],
  'notebookId' : NotebookId,
  'chapter' : [] | [string],
}
export interface Notebook {
  'id' : NotebookId,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
}
export type NotebookId = bigint;
export interface NotebookInput { 'title' : string, 'description' : string }
export interface NotebookSummary {
  'conversationCount' : bigint,
  'notebook' : Notebook,
  'sourceCount' : bigint,
  'flashcardCount' : bigint,
  'noteCount' : bigint,
  'quizCount' : bigint,
}
export interface NotebookUpdate {
  'title' : [] | [string],
  'description' : [] | [string],
}
export type ProgressId = bigint;
export type QuestionId = bigint;
export type QuestionKind = { 'mcq' : null } |
  { 'shortAnswer' : null } |
  { 'trueFalse' : null };
export interface Quiz {
  'id' : QuizId,
  'title' : string,
  'owner' : UserId,
  'difficulty' : QuizDifficulty,
  'createdAt' : Timestamp,
  'notebookId' : NotebookId,
}
export interface QuizAnswer {
  'questionId' : QuestionId,
  'selectedIndex' : bigint,
}
export type QuizDifficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export type QuizId = bigint;
export interface QuizQuestionView {
  'id' : QuestionId,
  'topic' : string,
  'kind' : QuestionKind,
  'prompt' : string,
  'options' : Array<string>,
}
export interface QuizRequest {
  'difficulty' : QuizDifficulty,
  'count' : bigint,
  'sourceId' : [] | [SourceId],
  'notebookId' : NotebookId,
  'kinds' : Array<QuestionKind>,
}
export interface QuizResult {
  'wrongCount' : bigint,
  'total' : bigint,
  'weakTopics' : Array<string>,
  'score' : bigint,
  'items' : Array<QuizResultItem>,
  'correctCount' : bigint,
  'quizId' : QuizId,
  'recommendedRevision' : Array<string>,
}
export interface QuizResultItem {
  'topic' : string,
  'correctIndex' : bigint,
  'explanation' : string,
  'correct' : boolean,
  'questionId' : QuestionId,
  'selectedIndex' : bigint,
  'prompt' : string,
}
export type Result = { 'ok' : QuizResult } |
  { 'err' : AppError };
export type Result_1 = { 'ok' : Source } |
  { 'err' : AppError };
export type Result_2 = { 'ok' : Quiz } |
  { 'err' : AppError };
export type Result_3 = { 'ok' : Note } |
  { 'err' : AppError };
export type Result_4 = { 'ok' : Array<Flashcard> } |
  { 'err' : AppError };
export type Result_5 = { 'ok' : Conversation } |
  { 'err' : AppError };
export type Result_6 = { 'ok' : Answer } |
  { 'err' : AppError };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__2 = { 'ok' : null } |
  { 'err' : Error };
export interface SearchHit {
  'id' : bigint,
  'title' : string,
  'kind' : string,
  'snippet' : string,
  'notebookId' : NotebookId,
}
export interface Source {
  'id' : SourceId,
  'url' : string,
  'status' : SourceStatus,
  'title' : string,
  'content' : string,
  'owner' : UserId,
  'kind' : SourceKind,
  'createdAt' : Timestamp,
  'errorMessage' : string,
  'updatedAt' : Timestamp,
  'storageKey' : string,
  'sizeBytes' : bigint,
  'notebookId' : NotebookId,
  'pageCount' : bigint,
}
export type SourceId = bigint;
export interface SourceInput {
  'url' : string,
  'title' : string,
  'content' : string,
  'kind' : SourceKind,
  'storageKey' : string,
  'sizeBytes' : bigint,
  'notebookId' : NotebookId,
}
export type SourceKind = { 'pdf' : null } |
  { 'url' : null } |
  { 'docx' : null } |
  { 'note' : null } |
  { 'pptx' : null } |
  { 'text' : null } |
  { 'youtube' : null };
export type SourceStatus = { 'pending' : null } |
  { 'processing' : null } |
  { 'ready' : null } |
  { 'failed' : null };
export interface SourceSummary { 'source' : Source, 'chunkCount' : bigint }
export type StudyMaterialKind = { 'quiz' : null } |
  { 'summary' : null } |
  { 'detailedNotes' : null } |
  { 'flashcards' : null };
export interface StudyProgress {
  'id' : ProgressId,
  'questionsAnswered' : bigint,
  'notesGenerated' : bigint,
  'owner' : UserId,
  'quizzesTaken' : bigint,
  'questionsCorrect' : bigint,
  'notebookId' : NotebookId,
  'lastActivityAt' : Timestamp,
  'flashcardsReviewed' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a source to one of the caller's notebooks.
   */
  'addSource' : ActorMethod<[SourceInput], Result_1>,
  /**
   * / Ask a question grounded in the notebook's sources.
   */
  'askQuestion' : ActorMethod<[ConversationId, string], Result_6>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Start a conversation inside one of the caller's notebooks.
   */
  'createConversation' : ActorMethod<[NotebookId, string], Result_5>,
  /**
   * / Create a notebook owned by the caller.
   */
  'createNotebook' : ActorMethod<[NotebookInput], Notebook>,
  /**
   * / Delete one of the caller's conversations and its messages.
   */
  'deleteConversation' : ActorMethod<[ConversationId], boolean>,
  /**
   * / Delete one of the caller's notes.
   */
  'deleteNote' : ActorMethod<[NoteId], boolean>,
  /**
   * / Delete one of the caller's notebooks and all data scoped to it.
   */
  'deleteNotebook' : ActorMethod<[NotebookId], boolean>,
  /**
   * / Delete one of the caller's sources and its chunks.
   */
  'deleteSource' : ActorMethod<[SourceId], boolean>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Generate flashcards for one of the caller's notebooks.
   */
  'generateFlashcards' : ActorMethod<[FlashcardRequest], Result_4>,
  /**
   * / Generate a note document for one of the caller's notebooks.
   */
  'generateNote' : ActorMethod<[NoteRequest], Result_3>,
  /**
   * / Generate a quiz for one of the caller's notebooks.
   */
  'generateQuiz' : ActorMethod<[QuizRequest], Result_2>,
  /**
   * / Static Markdown documentation of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch one of the caller's conversations.
   */
  'getConversation' : ActorMethod<[ConversationId], [] | [Conversation]>,
  /**
   * / Fetch one of the caller's notes.
   */
  'getNote' : ActorMethod<[NoteId], [] | [Note]>,
  /**
   * / Fetch one of the caller's notebooks.
   */
  'getNotebook' : ActorMethod<[NotebookId], [] | [Notebook]>,
  /**
   * / Fetch aggregate study progress for one of the caller's notebooks.
   */
  'getProgress' : ActorMethod<[NotebookId], [] | [StudyProgress]>,
  /**
   * / Fetch one of the caller's quizzes with its questions.
   */
  'getQuiz' : ActorMethod<[QuizId], [] | [[Quiz, Array<QuizQuestionView>]]>,
  /**
   * / Fetch one of the caller's sources.
   */
  'getSource' : ActorMethod<[SourceId], [] | [Source]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the chapters of one of the caller's notebooks.
   */
  'listChapters' : ActorMethod<[NotebookId], Array<Chapter>>,
  /**
   * / List the conversations of one of the caller's notebooks.
   */
  'listConversations' : ActorMethod<[NotebookId], Array<ConversationSummary>>,
  /**
   * / List the flashcards of one of the caller's notebooks.
   */
  'listFlashcards' : ActorMethod<[NotebookId], Array<Flashcard>>,
  /**
   * / List the messages of one of the caller's conversations.
   */
  'listMessages' : ActorMethod<[ConversationId], Array<Message>>,
  /**
   * / List the caller's notebooks with aggregate counts.
   */
  'listNotebooks' : ActorMethod<[], Array<NotebookSummary>>,
  /**
   * / List the notes of one of the caller's notebooks.
   */
  'listNotes' : ActorMethod<[NotebookId], Array<Note>>,
  /**
   * / List the quizzes of one of the caller's notebooks.
   */
  'listQuizzes' : ActorMethod<[NotebookId], Array<Quiz>>,
  /**
   * / List the sources of one of the caller's notebooks.
   */
  'listSources' : ActorMethod<[NotebookId], Array<SourceSummary>>,
  /**
   * / Send a source through the knowledge engine and record its status.
   */
  'processSource' : ActorMethod<[SourceId], Result_1>,
  /**
   * / Record a flashcard review outcome.
   */
  'reviewFlashcard' : ActorMethod<[FlashcardId, boolean], [] | [Flashcard]>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search the caller's notebooks, sources, notes, flashcards, conversations
   * / and quizzes.
   */
  'search' : ActorMethod<[string], Array<SearchHit>>,
  /**
   * / Seed the Indian Economy demo notebook for the caller if absent, and
   * / return it.
   */
  'seedDemoData' : ActorMethod<[], Notebook>,
  /**
   * / Replace the chapter list of one of the caller's notebooks.
   */
  'setChapters' : ActorMethod<[NotebookId, Array<string>], Array<Chapter>>,
  /**
   * / Submit answers to one of the caller's quizzes and receive a graded report.
   */
  'submitQuiz' : ActorMethod<[QuizId, Array<QuizAnswer>], Result>,
  /**
   * / Update one of the caller's notes.
   */
  'updateNote' : ActorMethod<
    [NoteId, [] | [string], [] | [string]],
    [] | [Note]
  >,
  /**
   * / Update one of the caller's notebooks.
   */
  'updateNotebook' : ActorMethod<[NotebookId, NotebookUpdate], [] | [Notebook]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];