/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Answer {
    assistantMessage: Message;
    userMessage: Message;
    conversationId: ConversationId;
}
export type AppError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "unsupportedSourceKind";
    unsupportedSourceKind: string;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "engineUnavailable";
    engineUnavailable: string;
} | {
    __kind__: "sourceTooLarge";
    sourceTooLarge: string;
};
export interface Cell {
    value: Value;
    name: string;
}
export interface Chapter {
    id: bigint;
    title: string;
    order: bigint;
    notebookId: NotebookId;
}
export interface Citation {
    sourceTitle: string;
    sourceId: SourceId;
    snippet: string;
}
export interface Conversation {
    id: ConversationId;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notebookId: NotebookId;
}
export type ConversationId = bigint;
export interface ConversationSummary {
    conversation: Conversation;
    messageCount: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Flashcard {
    id: FlashcardId;
    front: string;
    owner: UserId;
    back: string;
    createdAt: Timestamp;
    reviewCount: bigint;
    notebookId: NotebookId;
    lastReviewedAt?: Timestamp;
    knownCount: bigint;
}
export type FlashcardId = bigint;
export interface FlashcardRequest {
    difficulty: Difficulty;
    count: bigint;
    sourceId?: SourceId;
    notebookId: NotebookId;
}
export interface Message {
    id: MessageId;
    content: string;
    owner: UserId;
    createdAt: Timestamp;
    role: MessageRole;
    conversationId: ConversationId;
    citations: Array<Citation>;
    notebookId: NotebookId;
}
export type MessageId = bigint;
export interface Note {
    id: NoteId;
    title: string;
    content: string;
    owner: UserId;
    kind: StudyMaterialKind;
    difficulty: Difficulty;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notebookId: NotebookId;
}
export type NoteId = bigint;
export interface NoteRequest {
    kind: StudyMaterialKind;
    difficulty: Difficulty;
    sourceId?: SourceId;
    notebookId: NotebookId;
    chapter?: string;
}
export interface Notebook {
    id: NotebookId;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
}
export type NotebookId = bigint;
export interface NotebookInput {
    title: string;
    description: string;
}
export interface NotebookSummary {
    conversationCount: bigint;
    notebook: Notebook;
    sourceCount: bigint;
    flashcardCount: bigint;
    noteCount: bigint;
    quizCount: bigint;
}
export interface NotebookUpdate {
    title?: string;
    description?: string;
}
export type ProgressId = bigint;
export type QuestionId = bigint;
export interface Quiz {
    id: QuizId;
    title: string;
    owner: UserId;
    difficulty: QuizDifficulty;
    createdAt: Timestamp;
    notebookId: NotebookId;
}
export interface QuizAnswer {
    questionId: QuestionId;
    selectedIndex: bigint;
}
export type QuizId = bigint;
export interface QuizQuestionView {
    id: QuestionId;
    topic: string;
    kind: QuestionKind;
    prompt: string;
    options: Array<string>;
}
export interface QuizRequest {
    difficulty: QuizDifficulty;
    count: bigint;
    sourceId?: SourceId;
    notebookId: NotebookId;
    kinds: Array<QuestionKind>;
}
export interface QuizResult {
    wrongCount: bigint;
    total: bigint;
    weakTopics: Array<string>;
    score: bigint;
    items: Array<QuizResultItem>;
    correctCount: bigint;
    quizId: QuizId;
    recommendedRevision: Array<string>;
}
export interface QuizResultItem {
    topic: string;
    correctIndex: bigint;
    explanation: string;
    correct: boolean;
    questionId: QuestionId;
    selectedIndex: bigint;
    prompt: string;
}
export type Result = {
    __kind__: "ok";
    ok: QuizResult;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Source;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_2 = {
    __kind__: "ok";
    ok: Quiz;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_4 = {
    __kind__: "ok";
    ok: Array<Flashcard>;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_5 = {
    __kind__: "ok";
    ok: Conversation;
} | {
    __kind__: "err";
    err: AppError;
};
export type Result_6 = {
    __kind__: "ok";
    ok: Answer;
} | {
    __kind__: "err";
    err: AppError;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SearchHit {
    id: bigint;
    title: string;
    kind: string;
    snippet: string;
    notebookId: NotebookId;
}
export interface Source {
    id: SourceId;
    url: string;
    status: SourceStatus;
    title: string;
    content: string;
    owner: UserId;
    kind: SourceKind;
    createdAt: Timestamp;
    errorMessage: string;
    updatedAt: Timestamp;
    storageKey: string;
    sizeBytes: bigint;
    notebookId: NotebookId;
    pageCount: bigint;
}
export type SourceId = bigint;
export interface SourceInput {
    url: string;
    title: string;
    content: string;
    kind: SourceKind;
    storageKey: string;
    sizeBytes: bigint;
    notebookId: NotebookId;
}
export interface SourceSummary {
    source: Source;
    chunkCount: bigint;
}
export interface StudyProgress {
    id: ProgressId;
    questionsAnswered: bigint;
    notesGenerated: bigint;
    owner: UserId;
    quizzesTaken: bigint;
    questionsCorrect: bigint;
    notebookId: NotebookId;
    lastActivityAt: Timestamp;
    flashcardsReviewed: bigint;
}
export type Timestamp = bigint;
export type UserId = Principal;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum Difficulty {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    exam = "exam"
}
export enum MessageRole {
    user = "user",
    assistant = "assistant"
}
export enum QuestionKind {
    mcq = "mcq",
    shortAnswer = "shortAnswer",
    trueFalse = "trueFalse"
}
export enum QuizDifficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum SourceKind {
    pdf = "pdf",
    url = "url",
    docx = "docx",
    note = "note",
    pptx = "pptx",
    text = "text",
    youtube = "youtube"
}
export enum SourceStatus {
    pending = "pending",
    processing = "processing",
    ready = "ready",
    failed = "failed"
}
export enum StudyMaterialKind {
    quiz = "quiz",
    summary = "summary",
    detailedNotes = "detailedNotes",
    flashcards = "flashcards"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__2>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a source to one of the caller's notebooks.
     */
    addSource(input: SourceInput): Promise<Result_1>;
    /**
     * / Ask a question grounded in the notebook's sources.
     */
    askQuestion(conversationId: ConversationId, question: string): Promise<Result_6>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Start a conversation inside one of the caller's notebooks.
     */
    createConversation(notebookId: NotebookId, title: string): Promise<Result_5>;
    /**
     * / Create a notebook owned by the caller.
     */
    createNotebook(input: NotebookInput): Promise<Notebook>;
    /**
     * / Delete one of the caller's conversations and its messages.
     */
    deleteConversation(id: ConversationId): Promise<boolean>;
    /**
     * / Delete one of the caller's notes.
     */
    deleteNote(id: NoteId): Promise<boolean>;
    /**
     * / Delete one of the caller's notebooks and all data scoped to it.
     */
    deleteNotebook(id: NotebookId): Promise<boolean>;
    /**
     * / Delete one of the caller's sources and its chunks.
     */
    deleteSource(id: SourceId): Promise<boolean>;
    execute(qJson: string): Promise<Result__1>;
    /**
     * / Generate flashcards for one of the caller's notebooks.
     */
    generateFlashcards(request: FlashcardRequest): Promise<Result_4>;
    /**
     * / Generate a note document for one of the caller's notebooks.
     */
    generateNote(request: NoteRequest): Promise<Result_3>;
    /**
     * / Generate a quiz for one of the caller's notebooks.
     */
    generateQuiz(request: QuizRequest): Promise<Result_2>;
    /**
     * / Static Markdown documentation of this backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch one of the caller's conversations.
     */
    getConversation(id: ConversationId): Promise<Conversation | null>;
    /**
     * / Fetch one of the caller's notes.
     */
    getNote(id: NoteId): Promise<Note | null>;
    /**
     * / Fetch one of the caller's notebooks.
     */
    getNotebook(id: NotebookId): Promise<Notebook | null>;
    /**
     * / Fetch aggregate study progress for one of the caller's notebooks.
     */
    getProgress(notebookId: NotebookId): Promise<StudyProgress | null>;
    /**
     * / Fetch one of the caller's quizzes with its questions.
     */
    getQuiz(id: QuizId): Promise<[Quiz, Array<QuizQuestionView>] | null>;
    /**
     * / Fetch one of the caller's sources.
     */
    getSource(id: SourceId): Promise<Source | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the chapters of one of the caller's notebooks.
     */
    listChapters(notebookId: NotebookId): Promise<Array<Chapter>>;
    /**
     * / List the conversations of one of the caller's notebooks.
     */
    listConversations(notebookId: NotebookId): Promise<Array<ConversationSummary>>;
    /**
     * / List the flashcards of one of the caller's notebooks.
     */
    listFlashcards(notebookId: NotebookId): Promise<Array<Flashcard>>;
    /**
     * / List the messages of one of the caller's conversations.
     */
    listMessages(conversationId: ConversationId): Promise<Array<Message>>;
    /**
     * / List the caller's notebooks with aggregate counts.
     */
    listNotebooks(): Promise<Array<NotebookSummary>>;
    /**
     * / List the notes of one of the caller's notebooks.
     */
    listNotes(notebookId: NotebookId): Promise<Array<Note>>;
    /**
     * / List the quizzes of one of the caller's notebooks.
     */
    listQuizzes(notebookId: NotebookId): Promise<Array<Quiz>>;
    /**
     * / List the sources of one of the caller's notebooks.
     */
    listSources(notebookId: NotebookId): Promise<Array<SourceSummary>>;
    /**
     * / Send a source through the knowledge engine and record its status.
     */
    processSource(id: SourceId): Promise<Result_1>;
    /**
     * / Record a flashcard review outcome.
     */
    reviewFlashcard(id: FlashcardId, known: boolean): Promise<Flashcard | null>;
    schema(): Promise<string>;
    /**
     * / Search the caller's notebooks, sources, notes, flashcards, conversations
     * / and quizzes.
     */
    search(term: string): Promise<Array<SearchHit>>;
    /**
     * / Seed the Indian Economy demo notebook for the caller if absent, and
     * / return it.
     */
    seedDemoData(): Promise<Notebook>;
    /**
     * / Replace the chapter list of one of the caller's notebooks.
     */
    setChapters(notebookId: NotebookId, titles: Array<string>): Promise<Array<Chapter>>;
    /**
     * / Submit answers to one of the caller's quizzes and receive a graded report.
     */
    submitQuiz(quizId: QuizId, answers: Array<QuizAnswer>): Promise<Result>;
    /**
     * / Update one of the caller's notes.
     */
    updateNote(id: NoteId, title: string | null, content: string | null): Promise<Note | null>;
    /**
     * / Update one of the caller's notebooks.
     */
    updateNotebook(id: NotebookId, update: NotebookUpdate): Promise<Notebook | null>;
}
import type { Answer as _Answer, AppError as _AppError, Cell as _Cell, Citation as _Citation, Conversation as _Conversation, ConversationId as _ConversationId, Difficulty as _Difficulty, Error as _Error, Flashcard as _Flashcard, FlashcardId as _FlashcardId, FlashcardRequest as _FlashcardRequest, Message as _Message, MessageId as _MessageId, MessageRole as _MessageRole, Note as _Note, NoteId as _NoteId, NoteRequest as _NoteRequest, Notebook as _Notebook, NotebookId as _NotebookId, NotebookUpdate as _NotebookUpdate, QuestionId as _QuestionId, QuestionKind as _QuestionKind, Quiz as _Quiz, QuizDifficulty as _QuizDifficulty, QuizId as _QuizId, QuizQuestionView as _QuizQuestionView, QuizRequest as _QuizRequest, QuizResult as _QuizResult, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result__1 as _Result__1, Result__2 as _Result__2, Source as _Source, SourceId as _SourceId, SourceInput as _SourceInput, SourceKind as _SourceKind, SourceStatus as _SourceStatus, SourceSummary as _SourceSummary, StudyMaterialKind as _StudyMaterialKind, StudyProgress as _StudyProgress, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__2> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addSource(arg0: SourceInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addSource(to_candid_SourceInput_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSource(to_candid_SourceInput_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async askQuestion(arg0: ConversationId, arg1: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.askQuestion(arg0, arg1);
                return from_candid_Result_6_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askQuestion(arg0, arg1);
            return from_candid_Result_6_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createConversation(arg0: NotebookId, arg1: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0, arg1);
                return from_candid_Result_5_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0, arg1);
            return from_candid_Result_5_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotebook(arg0: NotebookInput): Promise<Notebook> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotebook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotebook(arg0);
            return result;
        }
    }
    async deleteConversation(arg0: ConversationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConversation(arg0);
            return result;
        }
    }
    async deleteNote(arg0: NoteId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteNotebook(arg0: NotebookId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotebook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotebook(arg0);
            return result;
        }
    }
    async deleteSource(arg0: SourceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSource(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateFlashcards(arg0: FlashcardRequest): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.generateFlashcards(to_candid_FlashcardRequest_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_4_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateFlashcards(to_candid_FlashcardRequest_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_4_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateNote(arg0: NoteRequest): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.generateNote(to_candid_NoteRequest_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_3_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateNote(to_candid_NoteRequest_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_3_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateQuiz(arg0: QuizRequest): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQuiz(to_candid_QuizRequest_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_2_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQuiz(to_candid_QuizRequest_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_2_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: ConversationId): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNote(arg0: NoteId): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotebook(arg0: NotebookId): Promise<Notebook | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotebook(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotebook(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(arg0: NotebookId): Promise<StudyProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuiz(arg0: QuizId): Promise<[Quiz, Array<QuizQuestionView>] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSource(arg0: SourceId): Promise<Source | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSource(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSource(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listChapters(arg0: NotebookId): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChapters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChapters(arg0);
            return result;
        }
    }
    async listConversations(arg0: NotebookId): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations(arg0);
            return result;
        }
    }
    async listFlashcards(arg0: NotebookId): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFlashcards(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFlashcards(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessages(arg0: ConversationId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessages(arg0);
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessages(arg0);
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotebooks(): Promise<Array<NotebookSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotebooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotebooks();
            return result;
        }
    }
    async listNotes(arg0: NotebookId): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotes(arg0);
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotes(arg0);
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuizzes(arg0: NotebookId): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuizzes(arg0);
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuizzes(arg0);
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSources(arg0: NotebookId): Promise<Array<SourceSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSources(arg0);
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSources(arg0);
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async processSource(arg0: SourceId): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.processSource(arg0);
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processSource(arg0);
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async reviewFlashcard(arg0: FlashcardId, arg1: boolean): Promise<Flashcard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewFlashcard(arg0, arg1);
                return from_candid_opt_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewFlashcard(arg0, arg1);
            return from_candid_opt_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async search(arg0: string): Promise<Array<SearchHit>> {
        if (this.processError) {
            try {
                const result = await this.actor.search(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.search(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<Notebook> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async setChapters(arg0: NotebookId, arg1: Array<string>): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.setChapters(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setChapters(arg0, arg1);
            return result;
        }
    }
    async submitQuiz(arg0: QuizId, arg1: Array<QuizAnswer>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0, arg1);
                return from_candid_Result_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0, arg1);
            return from_candid_Result_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: NoteId, arg1: string | null, arg2: string | null): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, to_candid_opt_n83(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n83(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, to_candid_opt_n83(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n83(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNotebook(arg0: NotebookId, arg1: NotebookUpdate): Promise<Notebook | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotebook(arg0, to_candid_NotebookUpdate_n84(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotebook(arg0, to_candid_NotebookUpdate_n84(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Answer_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Answer): Answer {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_AppError_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppError): AppError {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return "intermediate" in value ? Difficulty.intermediate : "beginner" in value ? Difficulty.beginner : "advanced" in value ? Difficulty.advanced : "exam" in value ? Difficulty.exam : value;
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Flashcard_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Flashcard): Flashcard {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return "user" in value ? MessageRole.user : "assistant" in value ? MessageRole.assistant : value;
}
function from_candid_Message_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionKind_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionKind): QuestionKind {
    return "mcq" in value ? QuestionKind.mcq : "shortAnswer" in value ? QuestionKind.shortAnswer : "trueFalse" in value ? QuestionKind.trueFalse : value;
}
function from_candid_QuizDifficulty_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizDifficulty): QuizDifficulty {
    return "easy" in value ? QuizDifficulty.easy : "hard" in value ? QuizDifficulty.hard : "medium" in value ? QuizDifficulty.medium : value;
}
function from_candid_QuizQuestionView_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizQuestionView): QuizQuestionView {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_Quiz_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quiz): Quiz {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Result__2_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__2): Result__2 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function from_candid_SourceKind_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceKind): SourceKind {
    return "pdf" in value ? SourceKind.pdf : "url" in value ? SourceKind.url : "docx" in value ? SourceKind.docx : "note" in value ? SourceKind.note : "pptx" in value ? SourceKind.pptx : "text" in value ? SourceKind.text : "youtube" in value ? SourceKind.youtube : value;
}
function from_candid_SourceStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceStatus): SourceStatus {
    return "pending" in value ? SourceStatus.pending : "processing" in value ? SourceStatus.processing : "ready" in value ? SourceStatus.ready : "failed" in value ? SourceStatus.failed : value;
}
function from_candid_SourceSummary_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceSummary): SourceSummary {
    return from_candid_record_n79(_uploadFile, _downloadFile, value);
}
function from_candid_Source_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Source): Source {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_StudyMaterialKind_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyMaterialKind): StudyMaterialKind {
    return "quiz" in value ? StudyMaterialKind.quiz : "summary" in value ? StudyMaterialKind.summary : "detailedNotes" in value ? StudyMaterialKind.detailedNotes : "flashcards" in value ? StudyMaterialKind.flashcards : value;
}
function from_candid_UserRole_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notebook]): Notebook | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyProgress]): StudyProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_Quiz, Array<_QuizQuestionView>]]): [Quiz, Array<QuizQuestionView>] | null {
    return value.length === 0 ? null : from_candid_tuple_n68(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Source]): Source | null {
    return value.length === 0 ? null : from_candid_Source_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Flashcard]): Flashcard | null {
    return value.length === 0 ? null : from_candid_Flashcard_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SourceId;
    url: string;
    status: _SourceStatus;
    title: string;
    content: string;
    owner: _UserId;
    kind: _SourceKind;
    createdAt: _Timestamp;
    errorMessage: string;
    updatedAt: _Timestamp;
    storageKey: string;
    sizeBytes: bigint;
    notebookId: _NotebookId;
    pageCount: bigint;
}): {
    id: SourceId;
    url: string;
    status: SourceStatus;
    title: string;
    content: string;
    owner: UserId;
    kind: SourceKind;
    createdAt: Timestamp;
    errorMessage: string;
    updatedAt: Timestamp;
    storageKey: string;
    sizeBytes: bigint;
    notebookId: NotebookId;
    pageCount: bigint;
} {
    return {
        id: value.id,
        url: value.url,
        status: from_candid_SourceStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        owner: value.owner,
        kind: from_candid_SourceKind_n13(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        errorMessage: value.errorMessage,
        updatedAt: value.updatedAt,
        storageKey: value.storageKey,
        sizeBytes: value.sizeBytes,
        notebookId: value.notebookId,
        pageCount: value.pageCount
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assistantMessage: _Message;
    userMessage: _Message;
    conversationId: _ConversationId;
}): {
    assistantMessage: Message;
    userMessage: Message;
    conversationId: ConversationId;
} {
    return {
        assistantMessage: from_candid_Message_n20(_uploadFile, _downloadFile, value.assistantMessage),
        userMessage: from_candid_Message_n20(_uploadFile, _downloadFile, value.userMessage),
        conversationId: value.conversationId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    owner: _UserId;
    createdAt: _Timestamp;
    role: _MessageRole;
    conversationId: _ConversationId;
    citations: Array<_Citation>;
    notebookId: _NotebookId;
}): {
    id: MessageId;
    content: string;
    owner: UserId;
    createdAt: Timestamp;
    role: MessageRole;
    conversationId: ConversationId;
    citations: Array<Citation>;
    notebookId: NotebookId;
} {
    return {
        id: value.id,
        content: value.content,
        owner: value.owner,
        createdAt: value.createdAt,
        role: from_candid_MessageRole_n22(_uploadFile, _downloadFile, value.role),
        conversationId: value.conversationId,
        citations: value.citations,
        notebookId: value.notebookId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n28(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n32(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FlashcardId;
    front: string;
    owner: _UserId;
    back: string;
    createdAt: _Timestamp;
    reviewCount: bigint;
    notebookId: _NotebookId;
    lastReviewedAt: [] | [_Timestamp];
    knownCount: bigint;
}): {
    id: FlashcardId;
    front: string;
    owner: UserId;
    back: string;
    createdAt: Timestamp;
    reviewCount: bigint;
    notebookId: NotebookId;
    lastReviewedAt?: Timestamp;
    knownCount: bigint;
} {
    return {
        id: value.id,
        front: value.front,
        owner: value.owner,
        back: value.back,
        createdAt: value.createdAt,
        reviewCount: value.reviewCount,
        notebookId: value.notebookId,
        lastReviewedAt: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.lastReviewedAt)),
        knownCount: value.knownCount
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoteId;
    title: string;
    content: string;
    owner: _UserId;
    kind: _StudyMaterialKind;
    difficulty: _Difficulty;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    notebookId: _NotebookId;
}): {
    id: NoteId;
    title: string;
    content: string;
    owner: UserId;
    kind: StudyMaterialKind;
    difficulty: Difficulty;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notebookId: NotebookId;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        owner: value.owner,
        kind: from_candid_StudyMaterialKind_n50(_uploadFile, _downloadFile, value.kind),
        difficulty: from_candid_Difficulty_n51(_uploadFile, _downloadFile, value.difficulty),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notebookId: value.notebookId
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuizId;
    title: string;
    owner: _UserId;
    difficulty: _QuizDifficulty;
    createdAt: _Timestamp;
    notebookId: _NotebookId;
}): {
    id: QuizId;
    title: string;
    owner: UserId;
    difficulty: QuizDifficulty;
    createdAt: Timestamp;
    notebookId: NotebookId;
} {
    return {
        id: value.id,
        title: value.title,
        owner: value.owner,
        difficulty: from_candid_QuizDifficulty_n61(_uploadFile, _downloadFile, value.difficulty),
        createdAt: value.createdAt,
        notebookId: value.notebookId
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuestionId;
    topic: string;
    kind: _QuestionKind;
    prompt: string;
    options: Array<string>;
}): {
    id: QuestionId;
    topic: string;
    kind: QuestionKind;
    prompt: string;
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        kind: from_candid_QuestionKind_n72(_uploadFile, _downloadFile, value.kind),
        prompt: value.prompt,
        options: value.options
    };
}
function from_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _Source;
    chunkCount: bigint;
}): {
    source: Source;
    chunkCount: bigint;
} {
    return {
        source: from_candid_Source_n10(_uploadFile, _downloadFile, value.source),
        chunkCount: value.chunkCount
    };
}
function from_candid_tuple_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Quiz, Array<_QuizQuestionView>]): [Quiz, Array<QuizQuestionView>] {
    return [
        from_candid_Quiz_n59(_uploadFile, _downloadFile, value[0]),
        from_candid_vec_n69(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    unsupportedSourceKind: string;
} | {
    invalidInput: string;
} | {
    notFound: string;
} | {
    engineUnavailable: string;
} | {
    sourceTooLarge: string;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "unsupportedSourceKind";
    unsupportedSourceKind: string;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: string;
} | {
    __kind__: "engineUnavailable";
    engineUnavailable: string;
} | {
    __kind__: "sourceTooLarge";
    sourceTooLarge: string;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "unsupportedSourceKind" in value ? {
        __kind__: "unsupportedSourceKind",
        unsupportedSourceKind: value.unsupportedSourceKind
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "engineUnavailable" in value ? {
        __kind__: "engineUnavailable",
        engineUnavailable: value.engineUnavailable
    } : "sourceTooLarge" in value ? {
        __kind__: "sourceTooLarge",
        sourceTooLarge: value.sourceTooLarge
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Answer;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Answer;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Answer_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Conversation;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Conversation;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Flashcard>;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Array<Flashcard>;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n39(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Note;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Note_n48(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Quiz;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Quiz;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Quiz_n59(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuizResult;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: QuizResult;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Source;
} | {
    err: _AppError;
}): {
    __kind__: "ok";
    ok: Source;
} | {
    __kind__: "err";
    err: AppError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Source_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AppError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Flashcard>): Array<Flashcard> {
    return value.map((x)=>from_candid_Flashcard_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuizQuestionView>): Array<QuizQuestionView> {
    return value.map((x)=>from_candid_QuizQuestionView_n70(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quiz>): Array<Quiz> {
    return value.map((x)=>from_candid_Quiz_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SourceSummary>): Array<SourceSummary> {
    return value.map((x)=>from_candid_SourceSummary_n78(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return value == Difficulty.intermediate ? {
        intermediate: null
    } : value == Difficulty.beginner ? {
        beginner: null
    } : value == Difficulty.advanced ? {
        advanced: null
    } : value == Difficulty.exam ? {
        exam: null
    } : value;
}
function to_candid_FlashcardRequest_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlashcardRequest): _FlashcardRequest {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_NoteRequest_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteRequest): _NoteRequest {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_NotebookUpdate_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotebookUpdate): _NotebookUpdate {
    return to_candid_record_n85(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionKind_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionKind): _QuestionKind {
    return value == QuestionKind.mcq ? {
        mcq: null
    } : value == QuestionKind.shortAnswer ? {
        shortAnswer: null
    } : value == QuestionKind.trueFalse ? {
        trueFalse: null
    } : value;
}
function to_candid_QuizDifficulty_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizDifficulty): _QuizDifficulty {
    return value == QuizDifficulty.easy ? {
        easy: null
    } : value == QuizDifficulty.hard ? {
        hard: null
    } : value == QuizDifficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_QuizRequest_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizRequest): _QuizRequest {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_SourceInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceInput): _SourceInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SourceKind_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceKind): _SourceKind {
    return value == SourceKind.pdf ? {
        pdf: null
    } : value == SourceKind.url ? {
        url: null
    } : value == SourceKind.docx ? {
        docx: null
    } : value == SourceKind.note ? {
        note: null
    } : value == SourceKind.pptx ? {
        pptx: null
    } : value == SourceKind.text ? {
        text: null
    } : value == SourceKind.youtube ? {
        youtube: null
    } : value;
}
function to_candid_StudyMaterialKind_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyMaterialKind): _StudyMaterialKind {
    return value == StudyMaterialKind.quiz ? {
        quiz: null
    } : value == StudyMaterialKind.summary ? {
        summary: null
    } : value == StudyMaterialKind.detailedNotes ? {
        detailedNotes: null
    } : value == StudyMaterialKind.flashcards ? {
        flashcards: null
    } : value;
}
function to_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    difficulty: Difficulty;
    count: bigint;
    sourceId?: SourceId;
    notebookId: NotebookId;
}): {
    difficulty: _Difficulty;
    count: bigint;
    sourceId: [] | [_SourceId];
    notebookId: _NotebookId;
} {
    return {
        difficulty: to_candid_Difficulty_n36(_uploadFile, _downloadFile, value.difficulty),
        count: value.count,
        sourceId: value.sourceId ? candid_some(value.sourceId) : candid_none(),
        notebookId: value.notebookId
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kind: StudyMaterialKind;
    difficulty: Difficulty;
    sourceId?: SourceId;
    notebookId: NotebookId;
    chapter?: string;
}): {
    kind: _StudyMaterialKind;
    difficulty: _Difficulty;
    sourceId: [] | [_SourceId];
    notebookId: _NotebookId;
    chapter: [] | [string];
} {
    return {
        kind: to_candid_StudyMaterialKind_n45(_uploadFile, _downloadFile, value.kind),
        difficulty: to_candid_Difficulty_n36(_uploadFile, _downloadFile, value.difficulty),
        sourceId: value.sourceId ? candid_some(value.sourceId) : candid_none(),
        notebookId: value.notebookId,
        chapter: value.chapter ? candid_some(value.chapter) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    difficulty: QuizDifficulty;
    count: bigint;
    sourceId?: SourceId;
    notebookId: NotebookId;
    kinds: Array<QuestionKind>;
}): {
    difficulty: _QuizDifficulty;
    count: bigint;
    sourceId: [] | [_SourceId];
    notebookId: _NotebookId;
    kinds: Array<_QuestionKind>;
} {
    return {
        difficulty: to_candid_QuizDifficulty_n54(_uploadFile, _downloadFile, value.difficulty),
        count: value.count,
        sourceId: value.sourceId ? candid_some(value.sourceId) : candid_none(),
        notebookId: value.notebookId,
        kinds: to_candid_vec_n55(_uploadFile, _downloadFile, value.kinds)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    content: string;
    kind: SourceKind;
    storageKey: string;
    sizeBytes: bigint;
    notebookId: NotebookId;
}): {
    url: string;
    title: string;
    content: string;
    kind: _SourceKind;
    storageKey: string;
    sizeBytes: bigint;
    notebookId: _NotebookId;
} {
    return {
        url: value.url,
        title: value.title,
        content: value.content,
        kind: to_candid_SourceKind_n7(_uploadFile, _downloadFile, value.kind),
        storageKey: value.storageKey,
        sizeBytes: value.sizeBytes,
        notebookId: value.notebookId
    };
}
function to_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    description?: string;
}): {
    title: [] | [string];
    description: [] | [string];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<QuestionKind>): Array<_QuestionKind> {
    return value.map((x)=>to_candid_QuestionKind_n56(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
